X(0) // not used
X(1) // heading
X(2)
X(3)
X(4)
X(5)
X(6)
X(ALT) // alternate service link
X(ASK) // link requiring input
X(BODY) // use body file in a template
X(BR) // line break
X(DATA) // send data to multi mode
X(E) // emphasis
X(ENV) // value of environment variable
X(F) // fixpitch
X(FI) // file info
X(FIS) // file info including size
X(FUR) // furigana
X(INC) // include file
X(INT) // interactive link
X(L) // link
X(N) // normal
X(PIPE) // include pipe
X(Q) // block quote
X(R) // reverse text direction
X(RAW) // include raw data from pipe
X(RAWI) // include raw inline delimited data
X(RGR) // reset graphic rendition
X(S) // strong
X(SET) // set environment variable
X(SGR) // set graphic rendition
X(TAB) // tab
X(X) // preformatted
