X(0) // not used
X(1) // heading
X(2)
X(3)
X(4)
X(5)
X(6)
X(ALT) // alternate service link
X(ASK) // link requiring input
X(BR) // line break
X(E) // emphasis
X(F) // fixpitch
X(FUR) // furigana
X(INC) // include file
X(INT) // interactive link
X(L) // link
X(N) // normal
X(PIPE) // include pipe
X(Q) // block quote
X(R) // reverse text direction
X(RGR) // reset graphic rendition
X(S) // strong
X(SGR) // set graphic rendition
X(TAB) // tab
X(X) // preformatted
