on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.repository_owner }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
